# Generated by Django 5.0.4 on 2024-06-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginForm',
            new_name='LoginModel',
        ),
    ]
